# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:   
  schedule:
    - cron: '*/16 0-8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run mju_notice_webhook.py
      run: |
        python mju_notice_webhook.py $URL
      env:
        MY_GITHUB_TOKEN: \$
    - name: Commit files
      env: 
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
      run: |
        git config --local user.email $MY_EMAIL
        git config --local user.name "dipito"
        git pull
        git add "recent.json"
        git commit -m "automatically updated" || echo failed
    - name: Update repository(Push)
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
